# railway.toml - backend .NET 8
[build]
builder = "NIXPACKS"
# Restaura pacotes e publica em Release na pasta ./publish
buildCommand = "dotnet restore && dotnet publish -c Release -o ./publish"
# Comando para rodar a API
startCommand = "dotnet ./publish/pcinx-api.dll"

[env]
# Força o Railway a usar o SDK .NET 8.0.115
DOTNET_VERSION = "8.0.115"
